# Generated by Django 4.2.16 on 2026-05-24 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dependents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                ("achievement_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=200)),
                ("icon", models.CharField(default="🏆", max_length=10)),
                ("xp_reward", models.IntegerField(default=0)),
                (
                    "badge_type",
                    models.CharField(
                        choices=[
                            ("bronze", "Bronze"),
                            ("silver", "Silver"),
                            ("gold", "Gold"),
                            ("platinum", "Platinum"),
                        ],
                        default="bronze",
                        max_length=20,
                    ),
                ),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("chores_completed", "Chores Completed"),
                            ("streak_days", "Streak Days"),
                            ("savings_amount", "Savings Amount"),
                            ("goals_reached", "Goals Reached"),
                            ("first_chore", "First Chore"),
                            ("first_goal", "First Goal"),
                            ("xp_points", "XP Points"),
                        ],
                        max_length=30,
                    ),
                ),
                ("trigger_value", models.IntegerField(default=1)),
                ("hint", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "db_table": "achievement",
                "ordering": ["trigger_value"],
            },
        ),
        migrations.CreateModel(
            name="UserAchievement",
            fields=[
                (
                    "user_achievement_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("earned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "achievement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="achievements.achievement",
                    ),
                ),
                (
                    "dependent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dependents.familydependent",
                    ),
                ),
            ],
            options={
                "db_table": "user_achievement",
                "ordering": ["-earned_at"],
                "unique_together": {("dependent", "achievement")},
            },
        ),
    ]
