# Generated by Django 4.2.16 on 2026-05-24 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dependents", "0001_initial"),
        ("heads", "0001_initial"),
        ("families", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chore",
            fields=[
                ("chore_id", models.AutoField(primary_key=True, serialize=False)),
                ("chore_name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("reward_amount", models.FloatField()),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        default="easy",
                        max_length=10,
                    ),
                ),
                ("deadline", models.DateField()),
                ("is_recurring", models.BooleanField(default=False)),
                (
                    "recurring_type",
                    models.CharField(
                        blank=True,
                        choices=[("weekly", "Weekly"), ("monthly", "Monthly")],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("pending_approval", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("archived", "Archived"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="heads.householdhead",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dependents.familydependent",
                    ),
                ),
            ],
            options={
                "db_table": "chore",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChoreCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("icon", models.CharField(default="🧹", max_length=10)),
                ("color", models.CharField(default="#1E1B4B", max_length=7)),
            ],
            options={
                "verbose_name_plural": "Chore Categories",
                "db_table": "chore_category",
            },
        ),
        migrations.CreateModel(
            name="ChoreSubmission",
            fields=[
                ("submission_id", models.AutoField(primary_key=True, serialize=False)),
                ("completion_notes", models.TextField()),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("is_approved", models.BooleanField(null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                (
                    "chore",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="chores.chore"
                    ),
                ),
                (
                    "dependent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dependents.familydependent",
                    ),
                ),
            ],
            options={
                "db_table": "chore_submission",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.AddField(
            model_name="chore",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="chores.chorecategory",
            ),
        ),
        migrations.AddField(
            model_name="chore",
            name="family",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="families.family"
            ),
        ),
    ]
