# Generated by Django 4.2.16 on 2026-05-24 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dependents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SavingsGoal",
            fields=[
                ("goal_id", models.AutoField(primary_key=True, serialize=False)),
                ("goal_name", models.CharField(max_length=200)),
                ("target_amount", models.FloatField()),
                ("current_amount", models.FloatField(default=0.0)),
                ("target_date", models.DateField(blank=True, null=True)),
                ("category", models.CharField(blank=True, max_length=50)),
                ("icon", models.CharField(default="🎯", max_length=10)),
                ("description", models.TextField(blank=True)),
                ("is_completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dependent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dependents.familydependent",
                    ),
                ),
            ],
            options={
                "db_table": "savings_goal",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GoalContribution",
            fields=[
                (
                    "contribution_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("amount", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="goals.savingsgoal",
                    ),
                ),
            ],
            options={
                "db_table": "goal_contribution",
                "ordering": ["-created_at"],
            },
        ),
    ]
