# Generated by Django 4.2.16 on 2026-05-24 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dependents", "0001_initial"),
        ("chores", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("transaction_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("reward", "Reward"),
                            ("allowance", "Allowance"),
                            ("expense", "Expense"),
                            ("adjustment", "Adjustment"),
                            ("savings", "Savings"),
                        ],
                        max_length=15,
                    ),
                ),
                ("amount", models.FloatField()),
                ("description", models.CharField(max_length=200)),
                ("category", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dependent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dependents.familydependent",
                    ),
                ),
                (
                    "reference_chore",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="chores.chore",
                    ),
                ),
            ],
            options={
                "db_table": "transaction",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AllowanceSchedule",
            fields=[
                ("schedule_id", models.AutoField(primary_key=True, serialize=False)),
                ("amount", models.FloatField()),
                (
                    "frequency",
                    models.CharField(
                        choices=[("weekly", "Weekly"), ("monthly", "Monthly")],
                        default="weekly",
                        max_length=10,
                    ),
                ),
                ("day_of_week", models.IntegerField(blank=True, null=True)),
                ("day_of_month", models.IntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("last_credited", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dependent",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dependents.familydependent",
                    ),
                ),
            ],
            options={
                "db_table": "allowance_schedule",
            },
        ),
    ]
