# Generated by Django 4.2.16 on 2026-05-24 16:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("families", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                ("plan_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("slug", models.SlugField(max_length=20, unique=True)),
                ("tagline", models.CharField(blank=True, max_length=200)),
                ("price_monthly", models.FloatField(default=0)),
                ("price_yearly", models.FloatField(default=0)),
                ("max_dependents", models.IntegerField(default=2)),
                ("max_chores", models.IntegerField(default=10)),
                ("max_goals", models.IntegerField(default=3)),
                ("has_ai", models.BooleanField(default=False)),
                ("has_analytics", models.BooleanField(default=False)),
                ("has_export", models.BooleanField(default=False)),
                ("has_achievements", models.BooleanField(default=False)),
                ("has_priority_support", models.BooleanField(default=False)),
                ("color", models.CharField(default="#1E1B4B", max_length=7)),
                ("icon", models.CharField(default="📦", max_length=10)),
                ("is_popular", models.BooleanField(default=False)),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "features",
                    models.TextField(blank=True, help_text="One feature per line"),
                ),
            ],
            options={
                "db_table": "plan",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "subscription_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[("monthly", "Monthly"), ("yearly", "Yearly")],
                        default="monthly",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                            ("trial", "Trial"),
                        ],
                        default="active",
                        max_length=15,
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("auto_renew", models.BooleanField(default=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "family",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="families.family",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="subscriptions.plan",
                    ),
                ),
            ],
            options={
                "db_table": "subscription",
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("payment_id", models.AutoField(primary_key=True, serialize=False)),
                ("billing_cycle", models.CharField(default="monthly", max_length=10)),
                ("amount", models.FloatField()),
                ("currency", models.CharField(default="INR", max_length=5)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("card", "Credit / Debit Card"),
                            ("upi", "UPI"),
                            ("netbanking", "Net Banking"),
                            ("wallet", "Wallet"),
                        ],
                        default="card",
                        max_length=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("pending", "Pending"),
                            ("refunded", "Refunded"),
                        ],
                        default="success",
                        max_length=10,
                    ),
                ),
                ("transaction_id", models.CharField(max_length=50, unique=True)),
                ("invoice_number", models.CharField(max_length=30, unique=True)),
                ("payer_name", models.CharField(blank=True, max_length=100)),
                ("last_four", models.CharField(blank=True, max_length=4)),
                ("upi_id", models.CharField(blank=True, max_length=100)),
                ("bank_name", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="subscriptions.plan",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="subscriptions.subscription",
                    ),
                ),
            ],
            options={
                "db_table": "payment",
                "ordering": ["-created_at"],
            },
        ),
    ]
