# Generated by Django 4.2.16 on 2026-05-24 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("families", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FamilyDependent",
            fields=[
                ("dependent_id", models.AutoField(primary_key=True, serialize=False)),
                ("full_name", models.CharField(max_length=100)),
                ("dob", models.DateField(blank=True, null=True)),
                (
                    "dependent_type",
                    models.CharField(
                        choices=[
                            ("child", "Child"),
                            ("teen", "Teen"),
                            ("young_adult", "Young Adult"),
                        ],
                        default="child",
                        max_length=15,
                    ),
                ),
                ("wallet_balance", models.FloatField(default=0.0)),
                ("xp_points", models.IntegerField(default=0)),
                ("streak_days", models.IntegerField(default=0)),
                ("last_activity", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="families.family",
                    ),
                ),
                (
                    "login",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="accounts.login"
                    ),
                ),
            ],
            options={
                "db_table": "family_dependent",
            },
        ),
    ]
