# Generated by Django 4.2.16 on 2026-05-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Family",
            fields=[
                ("family_id", models.AutoField(primary_key=True, serialize=False)),
                ("family_name", models.CharField(max_length=100)),
                ("join_pin", models.CharField(max_length=4)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "family",
            },
        ),
    ]
